howtos/setting_up_codacy_with_github.md

Providing style-check and coverage analysis on projects is a why to increase the code quality. I have written a howto on setting up Codacy with our Eiffel projects that I want to make available to other users. I hope this is correct place for such a howto.

Added a howto on integrating codacy with Eiffel github projects

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

eiffel-repository-template repo was not used when creating community repo so this change adds the issue and pull request templates in order to apply the existing/same way of working for this repo as well.

Add issue and pr templates

---

README.md

#58 
Make it easier to find CODE_OF_CONDUCT.md and CONTRIBUTING.md files and add an explanation of why they are in a different repository.
See issue referenced above
(c) …

Add section on default community health files

---

GOVERNANCE.md

#63 
This commit updates governance document, listing the members of Bootstrap Technical Committee (BTC) and chair who have been appointed during the Technical Committee (TC) meeting on [September 14th](https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ?view#September-14-2020).
N/A
Increased visibility and transparency.
N/A
work with modifications, whether created in …

List members and chair of bootstrap technical committee

---

SECURITY.md

fixes: #61 
This change proposes a lightweight security and vulnerability reporting proces.
N/A
The eiffel-community can use the process to receive and properly handle security and vulnerability issues.
None
permitted to submit under a different …

Add process for security and vulnerability reporting

---

README.md

#10 
It depends on https://github.com/eiffel-community/eiffel-community.github.io/pull/17
This change adds a link from README.md to the mission-and-vision.html page on the github.io site.
You could state the mission and vision directly in some .md file, but putting it on the github.io page provides greater visibility I think.
It solves #10
work with …

Added link to mission-and-vision.html

---

PROJECT_LIFECYCLE.md

New project proposals and proposals to move projects to different
lifecycle stages should be announced on Eiffel Community maillist
in order to increase the visibility.
Once the project creation or project lifecycle process is concluded,
TC chair sends an email to Eiffel Community maillist and announce
the new project or the lifecycle stage to broader Eiffel Community.
Closes AP from [TC meeting](https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ?view#Action-Items).
Project proposals and lifecycle stage changes are handled via GitHub issues in Eiffel Community community repository, which is not monitored by broader community.
In order to increase the visibility, transparency and community participation, it is important to announce this type of changes to the community on Eiffel Community Maillist. …

Add requirement to send mail to Eiffel Community maillist

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/general.md
.github/ISSUE_TEMPLATE/new_project.md
.github/PULL_REQUEST_TEMPLATE/general.md

Fixes #101
We copy the issue and PR templates from the .github repo in order to add a second issue template. This is unfortunately necessary since issue and PR templates are only inherited from the .github repo when the repo in question lacks templates entirely. See https://github.community/t/default-community-files-ignores-issue-templates/2802/7.
The new issue template will the "New issue" button (i.e. a visit to https://github.com/eiffel-community/community/issues/new/choose) to result in a menu where you can choose between creating a general issue and creating a request to create a new project. The section headings for the latter have been taken from PROJECT_LIFECYCLE.md.
None.
Easier for people to file project creation requests. Reduced risk of people filing incomplete such requests. …

Add "New project" issue template

---

GOVERNANCE.md

fixes #91 
Eiffel Community established and documented security/vulnerability reporting and response process.
This process is overseen by Eiffel Community Security Officers who are appointed by Eiffel Technical Committee.
This PR documents the role, responsibilities, and term of the Security officers together with the appointed community members in governance.
N/A
Increased transparency and communication.
N/A
license and I …

Document security officers, the role, and its responsibilities

---

meetings/MEETINGS_TC_2022.md
meetings/README.md

N/A
A new year requires a new HackMD document for the minutes of the TC meetings. This needs to be added to the meetings directory.
None.
Next year's TC meetings published like previous years'.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under …

Add new document for the 2022 TC meetings

---

GOVERNANCE.md

N/A
David has chosen to leave the technical committee so he should be removed from the table of TC members.
Considered leaving breadcrumbs to indicate that he was duly elected but chose to leave, but figured that we have the git history for that. The TC membership table should reflect the current reality.
Governance document reflects reality.
None
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that …

GOVERNANCE.md: Remove David Westberg from TC member table

---

GOVERNANCE.md

N/A; following decision made at the [2021-12-02 TC meeting](https://github.com/eiffel-community/community/blob/master/meetings/MEETINGS_TC_2021.md#december-02-2021).
The TC decided that it makes sense to have the members' email addresses visible along with their GitHub handles. Also included the TC mailing list address.
None.
Easier to get in contact with the TC.
Might expose TC members to more spam.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license …

GOVERNANCE.md: Add TC member's email addresses

---

GOVERNANCE.md

[141](https://github.com/eiffel-community/community/issues/141)
Update security officer description to better show that security officers can inform and support repository maintainers but security officers do not have a responsibility to fix security issues in the repositories.
Keep as is, but this gives the impression of a responsibility that can't be fulfilled today.
Well defined role description
N/A
license and I have …

Update security officer description

---

GOVERNANCE.md

N/A
Since Azeem nowadays is an Ericsson employee (from which we already have two TC representatives) he'll cede his spot in the TC.
None.
TC membership list reflects reality.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different …

GOVERNANCE.md: Remove Azeem from TC

---

meetings/MEETINGS_TC_2023.md
meetings/README.md

N/A
The new MoM document has been prepopulated with the preliminary agenda of this year's first TC meeting on Jan 11.
Last year we reached the size limit of HackMD documents and had to split the document in two. This isn't being done upfront for 2023 since we've changed how actions are tracked (we now primarily use GitHub issues) so it's unlikely we'll hit the limit again.
None.
Syncing of the HackMD document for the TC meeting MoM will continue to work.
None.
(b) The contribution is based upon previous work that, to the best    of my …

Add new document for the 2023 TC meetings

---

GOVERNANCE.md

Fixes #137 
Specifying the end-of-term dates for the current election and security officers. The term for the security officers was decided at the 2022-08-25 TC meeting. The appointment of the election officers wasn't clearly documented so the 2022-01-27 TC meeting where Fatih clearly acted as an election officer was taken as the date of appointment.
None.
It's clearly useful for elected and appointed officials to have their terms stated somewhere.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is …

GOVERNANCE.md: Add end date for election and security officers

---

GOVERNANCE.md

Eiffel-community/community#141
Added information about the maintainer responsibilities with emphasis on details regarding security and vulnerabilities
N/A
Easier for new (and old?) maintainers to understand their responsibilities
None that I can see
by me, under the same open source license (unless I …

Clarify maintainer responsibilities

---

meetings/MEETINGS_TC_2024.md
meetings/README.md

N/A; change is trivial and of administrative nature
New year, new TC meeting minutes document in HackMD and a new file in the meetings directory. The added 2024 file in the git is based on the existing HackMD document (which is reused each year to have consistent links to the current MoM document) and has been prepopulated with the preliminary agenda of this year's first TC meeting on Jan 11.
None.
Allows us to continue recording our meetings on GitHub. Can't continue with the 2023 document because of HackMD's size limit.
None.
(b) The …

Add new document for the 2024 TC meetings

---

meetings/MEETINGS_TC_2025.md
meetings/README.md

N/A; change is trivial and of administrative nature
New year, new TC meeting minutes document in HackMD and a new file in the meetings directory. The added 2025 file in the git is based on the existing HackMD document (which is reused each year to have consistent links to the current MoM document) and has been prepopulated with the preliminary agenda of this year's first TC meeting on Jan 9.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license …

Add new document for the 2025 TC meetings

---

presentations/README.md

Fixes #197
Adds a README files to the [presentations directory](https://github.com/eiffel-community/community/tree/master/presentations) to make it more clear what's stored there, and to give an opportunity to link to the YouTube channel.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source …

Add presentations/README.md

---

GOVERNANCE.md

Fixes #193
Removing the email addresses makes it slightly harder to harvest them for nefarious purposes. We still include people's GitHub profile where people can choose to include their email address, to the extent they're needed given other possible avenues of contact.
None.
Could make it slightly harder to reach people.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with …

GOVERNANCE.md: Remove email addresses

---

GOVERNANCE.md

Fixes #212
As discussed at the [2024-03-27 TC meeting](https://github.com/eiffel-community/community/blob/master/meetings/MEETINGS_TC_2024.md#March-27-2024), only maintainers of non-archived projects should be eligible to the TC (with the possibility of exemptions).
None.
None. There's an exemption process we can use if necessary.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with …

GOVERNANCE.md: Limit TC eligibles to maintainers of non-archived repos

---

GOVERNANCE.md
RESOURCES.md

N/A; executing [post-election checklist](https://github.com/eiffel-community/community/blob/master/howtos/post-tc-election-checklist.md)
After the 2025 TC elections, remove @e-backmark-ericsson from the TC and clear out the TC chairs as none will be elected this year.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by …

Update TC members after elections
