GOVERNANCE.md

#2 
Replaces #18 due to a messy situation with added and removed files that should not have been part of this PR. Details can be provided on demand, otherwise I will just leave it at that.
* Replaces #18 due to some git mess that was too hard to get out of.
* Fixes for (hopefully) all comments related to GOVERNANCE.md that was
voiced in #18.
* Closes #2.
Note: this is mostly not my work, I only repackage the PR and updated the GOVERNANCE.md file to (hopfully) satisfy some comments.
-
We get a clean PR with only the GOVERNANCE.md for review so that reviewers do not have to spend time on other documents already merged.
It might be a touch confusing to have two PR:s regarding the same topic, but I will close the other just after creating this.
By making …

Add governance draft

---

README.md

Just a simple spelling/grammar update
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) …

Update spelling/grammar in README.md

---

howtos/working_with_community-logos.md

#37
A howto is added, describing how to work with the logo file in Gimp and how to export logos to different formats.
-
Make it easier
-
(c) The contribution was provided …

Add howto for logo

---

CONTACT.md
README.md

Fixes #33
Add Slack information to README.
Reference the CONTACT from README so it's more visible 
(c) The contribution was provided directly to me by some other
person …

Add Slack in README

---

PROJECT_LIFECYCLE.md

https://github.com/eiffel-community/community/issues/5
https://github.com/eiffel-community/eiffel-repository-template/issues/9
Eiffel Community is organized around Git repositories and how those repositories relate to each other is not very clear for user perspective since one repository may be part of a project which consists of multiple repositories. In order for the community to determine what projects are hosted, the community first needs to document the fact that EIffel Community is organized around projects which may well consist of multiple repositories.
In addition to how the community is organized, there is no easy way for the community and users to know what stage those projects are in their lifecycle. This is an important aspect to know for users to decide whether they should …

Take first stab on project lifecycle

---

README.md

#49 
This change adds MEETINGS.md file to be used by and for Technical Committee meetings. The file is currently empty as it is expected to be updated using HackMD.io. In order for that to happen, the file must exist first so HackMD.io can be granted push access. 
The notes on HackMD.io is available on this link: https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ
It is also important to note that when meeting notes are updated on HackMD.io and pushed to the repo, the push is done by a bot.
In addition to creating MEETINGS.md file, it is linked from the repo README.md file for ease of access.
Keeping and working with the notes directly from the Git Repository.
However, this limits the collaboration while working with meeting minutes GitHub does not offer collaborative editing capabilities.
Increased …

Add MEETINGS.md

---

PROJECT_LIFECYCLE.md

N/A
Fix so that the links pointing to a non-existing "projects.md" are changed to "PROJECTS.md" instead.
N/A
Links should be correct in the documents
None
(c) The …

Fix links in the PROJECT_LIFECYCLE document

---

GOVERNANCE.md

TC members have permission to review, approve, and accept PRs
coming to specific repositories. This commit lists these repos.
Closes #69 
Update governance document and list the repos which the TC members have permission to review, approve, and accept PRs.
N/A
Increase visibility.
N/A
by me, under the …

Add list of repos the TC members have permissions on

---

PROJECT_LIFECYCLE.md

Documents https://github.com/eiffel-community/eiffel-repository-template/issues/9
Add examples of how to use badges for the different stages
I can't think of any better place to document this.
Documentation of the agreed solution
None of what I can think of
by me, under the same open source license …

Add examples of how to use badges for the different stages

---

howtos/add-new-repository.md

Closes #83 
New repo creation howto document is outdated and does not contain information about when the described process could be followed.
Based on the work Eiffel BTC did, the creation of new projects are done following the process described in project lifecycle document so this commit adds a note together with the links to corresponding documentation in howto document.
None
Updated instructions.
None
license and I …

Update new repo creation howto be inline with project lifecycle process

---

GOVERNANCE.md

Closes #81.
Eiffel Community will move to a meritocratic Technical Committee during 2021Q1.
It is necessary to document Election Process together with roles, rules, and exceptions so the community is aware of the election process adopted by the community.
This PR replaces PR #82 since it got messed up due to issues with the fork.
The updates to GOVERNANCE.md is same as the one in PR #82 which is currently being reviewed.
N/A
Election process, including roles, rules, and exceptions documented.
N/A
(b) The contribution is based upon previous work …

Take first stab in TC Election Process

---

GOVERNANCE.md

#87
Document appointed Eiffel Community Elections Officers as agreed by Eiffel Bootstrap Technical Committee during [its meeting](https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ#March-25-2021) on March 25, 2021.
N/A
Election Officers are recorded.
N/A …

Document Election Officers

---

GOVERNANCE.md

fixes #87 and #88.
Create a file named ELECTIONS.md in the repo as a placeholder in order to connect the file from [HackMD.io](https://hackmd.io/6x1Ef5Y_RWqaOmytMeYVKw?view) to the repository.
File can be kept in and worked on directly in the repository.
Keeping the document on HackMD.io and working it there is relatively easier since these documents are frequently updated in nature.
The docs could get out of sync if one person modifies it on HackMD.io and another in Git repo.
The community needs to work on with only single document on HackMD.io which is already what Eiffel TC is used to doing as can be seen by TC Meeting Agenda and Minutes.
(a) The contribution was created in whole or in part …

Create ELECTIONS.md as a placeholder

---

GOVERNANCE.md

AP from TC meeting [May 6th](https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ?view#May-6-2021)
State that we have two chairs in the TC
N/A
Update the governance to reflect the reality
N/A
in the …

State that we have two chairs in the TC

---

GOVERNANCE.md

AP from TC meeting [May 6th](https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ?view#May-6-2021)
Specify how many votes a community repo PR must have before merging
N/A
More clear description of the process
N/A
permitted to submit under a different …

Specify voting rules for PR in the community repo

---

GOVERNANCE.md

N/A; trivial
The 2021-05-06 Technical Committee meeting decided that GOVERNANCE.md should not only list the TC members but also the chairs. This PR makes it so.
None.
Clearer who the TC chairs are.
None
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit …

GOVERNANCE.md: Add list of elected chairs

---

GOVERNANCE.md

Fixes #109 
Added one line to point to the contribution guidelines in the .github repository
Not that I can think of
The reader knows about the contribution guidelines directly
Non that I can think of
permitted to submit under a different …

Add link to the contribution guidelines

---

howtos/introduction-of-a-new-tc-member.md

[Action Item](https://hackmd.io/@eiffel-community/r1_qm09zw#Action-Items) from TC meeting
Add a checklist for new TC members
None
We will not forget what access a new TC member needs
None
permitted to submit under a different license), as …

Add a checklist for new TC members

---

howtos/how-to-handle-graphical-images.md

Action item from TC
Documenting how images should be handled within the Eiffel Community
N/A
Guidelines for handling graphical images
N/A
(c) The contribution was …

Add description on handling images

---

PROJECT_LIFECYCLE.md

#123 
Updates the current instruction on how to create a new project in the Eiffel Community GitHub organization
-
Clarity
None
(c) The contribution was provided directly …

Update instruction for new project creation

---

ELECTIONS.md
GOVERNANCE.md

N/A
The TC elections checklist is completed and the TC and TC chairs tables are updated with new dates and the new TC member Azeem Ahmad.
Also updated the company for Tobias and Magnus whose employer is Axis Communications, not Axis which is the holding company of the former.
None.
Up to date TC information.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether …

GOVERNANCE.md: Update with new TC

---

howtos/how-to-handle-graphical-images.md

N/A
Att ETOS logo to the list of logos
None
Visibility
None
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have …

Add ETOS logo

---

howtos/introduction-of-a-new-tc-member.md

N/A; follows from [TC meeting decisions](https://hackmd.io/@eiffel-community/H1nsAQ1iK).
Remove irrelevant billing email item (mailing list address used instead), and add items for access to LinkedIn page, Slack workspace, and TC tasks GitHub project.
None.
Smoother TC roster transitions.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or …

Update the new TC member checklist

---

GOVERNANCE.md

Fixes #135 
When SECURITY.md was moved to the .github repository and removed from this repository in #128 we forgot to update the link to it in GOVERNANCE.md.
None.
No dead links.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different …

GOVERNANCE.md: Fix broken link to security process

---

howtos/post-tc-election-checklist.md

Fixes #146 
Added a TC post election checklist in the `howto` folder containing tasks to perform
We could have merged this with https://github.com/eiffel-community/community/blob/master/howtos/update-tc-members.md but that list covers needs for one person whereas this list covers task for the TC.
To not forget any important steps to be performed by the new TC
None that I can think of
license and I have the right under that …

Add Post TC election checklist

---

GOVERNANCE.md

Closes #164 
Updates to the GOVERNANCE.md document to clarify the TC election process, including the review of the eligible candidates list. This PR goes hand-in-hand with the updates to the ELECTIONS.md document seen [here](https://github.com/eiffel-community/community/commit/63b4e9763ca180b99c1335e67dafeb644f4d680c) and [here](https://github.com/eiffel-community/community/commit/824a2cc97752b262e82979bfa5fb260378182662) (updated through HackMD).
N/A
Clearer election process, and no duplication 
none
(b) The contribution is based upon previous …

Update GOVERNANCE.md on election details

---

GOVERNANCE.md

Fixes #93
The GOVERNANCE.md document do not reflect the actual way of working with maintainers and CODEOWNERS file. We do not use the CODEOWNERS file to keep track of the repository maintainers, but instead use GitHub's built in functionality of maintainer lists. This change reflect this.
We get a less confusing process of adding maintainers, and a more clearly defined election process (since only maintainers are allowed to be nominated to the Technical Community.
of my knowledge, …

Change how to become a maintainer

---

GOVERNANCE.md

Fixes #191
At the [TC meeting on 2024-01-18](https://github.com/eiffel-community/community/blob/master/meetings/MEETINGS_TC_2024.md#January-18-2024), Fredrik Fristedt and Fatih Degirmenci were appointed Election Officers for another term, ending 2025-01-31. [GOVERNANCE.md](https://github.com/eiffel-community/community/blob/master/GOVERNANCE.md) is updated accordingly.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right …

GOVERNANCE.md: New term for election officers

---

ELECTIONS.md
GOVERNANCE.md
meetings/MEETINGS_BTC.md
meetings/MEETINGS_TC_2022_1H.md

N/A; we're just correcting misspellings
Mattias Linnér's name had been misspelled Linnèr in a number of places. Let's correct all the occurrences in plain text files.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), …

Correct misspellings of Mattias Linnér's last name

---

GOVERNANCE.md
howtos/post-tc-election-checklist.md

Task from the Eiffel TC meeting - See Task from https://github.com/eiffel-community/community/blob/master/meetings/MEETINGS_TC_2024.md#october-2-2024
- Update dates to reflect the new period
- Update the post election checklist to update the governance document
N/A
N/A
by me, under the same open …

Updates from the 2024 elections

---

PROJECT_LIFECYCLE.md

Closes https://github.com/eiffel-community/community/issues/148
Added a process on how to archive a repository so we can have a checklist to go by when archiving repositories
Removing the google group might be to harsh but I was worried that a lingering google group could create confusion.
None that I can think of
work with modifications, whether created in …

Add instructions how to archive a repo

---

howtos/update-tc-members.md

Fixes #217 
Add an item to the  [TC members update checklist](https://github.com/eiffel-community/community/blob/master/howtos/update-tc-members.md) to remind people to update RESOURCES.md based on the new TC composition.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless …

Add "update RESOURCES.md" to Update TC members checklist

---

GOVERNANCE.md

N/A; follows decision at [the 2025-01-23 TC meeting](https://github.com/eiffel-community/community/blob/master/meetings/MEETINGS_TC_2025.md#january-23-2025).
An election officer was appointed in January and we forgot to update this document. Better late than never.
None.
None.
by me, under the same …

GOVERNANCE.md: Update list of current election officers
